import { Meta, StoryObj } from '@storybook/react-vite';
import { SearchResultsListWidgetProps } from '@ts4nfdi/terminology-service-suite/src';
declare const meta: Meta<SearchResultsListWidgetProps>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const SearchResultsListSafety: Story;
export declare const SearchResultsListNFDI4Health: Story;
export declare const ErrorSearchResultsList: Story;
export declare const TibNFDI4CHEM: Story;
export declare const TibDataPlant: Story;
export declare const SearchResultsListOls4: Story;
