import { Meta, StoryObj } from '@storybook/react';
declare const meta: Meta;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const OEO_00000150: Story;
export declare const Q259745: Story;
export declare const Energy: Story;
export declare const Rec_B_2000: Story;
export declare const Ges_C_2700: Story;
export declare const B14C4A: Story;
