import { Meta, StoryObj } from '@storybook/react-vite';
import { HierarchyWidgetProps } from '@ts4nfdi/terminology-service-suite/src';
declare const meta: Meta<HierarchyWidgetProps>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const ClassHierarchy: Story;
export declare const IndividualHierarchy: Story;
export declare const PreferredRoots: Story;
export declare const IncludeObsoleteEntities: Story;
export declare const PropertyRoots: Story;
export declare const IndividualRoots: Story;
export declare const LargeHierarchy: Story;
export declare const SkosHierarchy: Story;
export declare const SagePubHierarchy: Story;
export declare const OntoportalHierarchy: Story;
export declare const OLS3Hierarchy: Story;
export declare const OLSGerman: Story;
export declare const SkosmosAgrovocGerman: Story;
export declare const CompareHierarchies: Story;
export declare const CompareHierarchiesSubEntity: Story;
